### ISSUE TITLE
[SOLVED] proper steps to build/use/install your modified bullseye brickman?

### ISSUE THREAD

**Issue by Growflavor** [StepanTheFlowey/brickman#1]
Hi!

@StepanTheFlowey 
1) My son & I would be very grateful to learn how to update to your brickman 0.11.0 since these look like great updates:

`brickman (0.11.0+fl0wey1) UNRELEASED; urgency=medium

  * Non-maintainer upload.
  * Local changes.

 -- Flowey <stepanmasirov@gmail.com>  Sat, 27 Jan 2024 18:25:40 +0000

brickman (0.11.0) bullseye; urgency=medium

  * lib/connman/Service: add new mDNS properties
  * BluetoothController: fix critical message due to missing sysfs attribute
  * Fix all of the DBusError warnings
  * Fix warnings about deprecated Posix.SIG*
  * Fix errors about ambiguous Uuid type
  * fix error where default is not allowed with custom get/set in property
  * Fix warning about deprecated DBusObjectManagerClient.new_for_bus method
  * Fix all warnings about [Deprecated] attribute
  * ConnmanAgent: fix C compiler error due to bad generated code
  * fix multiple entries of same file in file browser
  * openroberta: don't switch consoles
  * openroberta: restore LEDs to normal after run`

2) We are using the default Bullseye beta2 EV3dev image -- we've updated sources.list & packages & added the various required dev build tools:

Linux ev3dev 4.19.85-ev3dev-3-beta2-ev3 #1 PREEMPT Sun Nov 24 16:49:49 CST 2019
Debian bullseye on LEGO MINDSTORMS EV3! armv5tejl

3) Our attempts so far to 'make' brickman from the clone of your git seem to succeed & create a new brickman file.  However we do not know how to .deb package or install the new brickman 0.11.0 (also we noticed the file size is about 1/2). 

`-rwxr-xr-x  1 root root 445428 Mar 22 07:52 brickman

vs:
-rwxr-xr-x 1 root  root  908792 Mar 22 23:34 brickman (0.10.2)
-rw-r--r-- 1 robot robot 203138 Sep  4  2019 brickman_0.10.2_armel.deb`

We are new to cmake & make as well as to updating system service related files & are clearly still missing key aspects of the process.

We would very much appreciate the key proper steps & commands sequence that you recommend that we use to make & use/'install' your version.

Thank you!

@dlech
Would also be grateful for your insights on how to install an updated Brickman made from source.  I did try making from source your Brickman 0.10.2 but also could not figure out what I need to do to be able to install a 'made from source' brickman -- I see there is a debian folder with control etc so I am hopeful there is a simple process/command we should run to build a .deb package that we can then use apt or dpkg to install (though I did not see any CPAK lines in the CMakeLists.txt).  Thanks!

**Comment by StepanTheFlowey** [comment]
> since these look like great updates

Yea... i will change it.

> However we do not know how to .deb package

As far as I can remember i used 'dpkg-buildpackage'. It should create the .deb file in parent directory. This file can be installed by 'sudo dpkg -i *.deb' command.

I will update README when i have time.

**Comment by Growflavor** [comment]
Great!  Thank you --that method appears to work much better...In our 'virtual bullseye EV3' docker container I simply:

robot@9fb851ea098a:/usr/local/src$ sudo git clone --recurse-submodules https://github.com/StepanTheFlowey/brickman.git

robot@9fb851ea098a:/usr/local/src/brickman$ sudo dpkg-buildpackage -us -uc

and now have a nice larger brickman file & new .deb:

-rwxr-xr-x 1 root root 584808 Mar 24 22:48 brickman
-rw-r--r--  1 root root 156296 Mar 24 22:48 brickman_0.11.0+fl0wey1_armel.deb

![Debbuild](https://github.com/StepanTheFlowey/brickman/assets/1580559/26e9ab77-16db-4bd3-b89c-b0fc3e3915cb)

When my son wakes up, I look forward to installing this new brickman via the brickman_0.11.0+fl0wey1_armel.deb!  Will post an update after the install :-)

**Comment by Growflavor** [comment]
Thank you very much for making a working Bullseye Brickman 0.11.0 !! :-)

For anyone else using Bullseye with EV3: 

I used [brickstrap](https://github.com/ev3dev/brickstrap/issues/73#issuecomment-2005726605) to make an .img of the same Debian 11 docker container that we had updated & used to successfully build @StepanTheFlowey 's Brickman 0.11.0.

We then successfully used Balena Etcher to flash that brickstrap .img to a SDcard & booted the EV3:

========== ev3dev-sysinfo ==========
Image file:         ev3dev-bullseye-ev3-generic-2021-05-10
Kernel version:     4.19.85-ev3dev-3-beta2-ev3
Brickman:           0.11.0+fl0wey1
BogoMIPS:           148.88
Bluetooth:          4.0
Board:              board0
BOARD_INFO_HW_REV=8
BOARD_INFO_MODEL=LEGO MINDSTORMS EV3
BOARD_INFO_ROM_REV=6
BOARD_INFO_SERIAL_NUM=00165360CCF6
BOARD_INFO_TYPE=main

Brickman 0.11.0 looks nice & enabled us to connect to bluetooth for the first time with EV3 on Debian Bullseye beta2! 
(for us, the brickman 0.10.2 that came with the default docker pull for EV3 bullseye beta2 never showed text)

![Brickman0110eg](https://github.com/StepanTheFlowey/brickman/assets/1580559/f3be683f-01e0-4ec0-8c46-bba6bebf2712)

**Comment by StepanTheFlowey** [comment]
I updated readme, changelog and published built .deb.

**Comment by StepanTheFlowey** [comment]
> Brickman 0.11.0 looks nice

that's was done by me)
that's the reason i did the fork

**Comment by Growflavor** [comment]
> > Brickman 0.11.0 looks nice
> > that's was done by me) that's the reason i did the fork

@StepanTheFlowey   yes :-)  & I am very very grateful for your updated Brickman 0.11.0 that works with (at least the old) Bullseye kernel.  Thank you!

**Comment by Nikolay-Zagrebin** [comment]
> Thank you very much for making a working Bullseye Brickman 0.11.0 !! :-)
> 
> For anyone else using Bullseye with EV3:
> 
> I used [brickstrap](https://github.com/ev3dev/brickstrap/issues/73#issuecomment-2005726605) to make an .img of the same Debian 11 docker container that we had updated & used to successfully build @StepanTheFlowey 's Brickman 0.11.0.
> 
> We then successfully used Balena Etcher to flash that brickstrap .img to a SDcard & booted the EV3:
> 
> ========== ev3dev-sysinfo ========== Image file: ev3dev-bullseye-ev3-generic-2021-05-10 Kernel version: 4.19.85-ev3dev-3-beta2-ev3 Brickman: 0.11.0+fl0wey1 BogoMIPS: 148.88 Bluetooth: 4.0 Board: board0 BOARD_INFO_HW_REV=8 BOARD_INFO_MODEL=LEGO MINDSTORMS EV3 BOARD_INFO_ROM_REV=6 BOARD_INFO_SERIAL_NUM=00165360CCF6 BOARD_INFO_TYPE=main
> 
> Brickman 0.11.0 looks nice & enabled us to connect to bluetooth for the first time with EV3 on Debian Bullseye beta2! (for us, the brickman 0.10.2 that came with the default docker pull for EV3 bullseye beta2 never showed text)
> 
> ![Brickman0110eg](https://private-user-images.githubusercontent.com/1580559/316624733-f3be683f-01e0-4ec0-8c46-bba6bebf2712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTk5MjYsIm5iZiI6MTcxODM1OTYyNiwicGF0aCI6Ii8xNTgwNTU5LzMxNjYyNDczMy1mM2JlNjgzZi0wMWUwLTRlYzAtOGM0Ni1iYmE2YmViZjI3MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMTAwNzA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWRmNjA4MmU3NGRhZWQ4OTlmODEyNDJiZTdlNGUzYTVjOTIxNjg0MjljYzkxN2U3MjAzNzA2OTkwNjZhY2YxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.55Rx8x2Bgm-T9mpj34qfO2ar9SweU9OppDFK0Gn9ox8)

I do everything according to the instructions, the whole installation goes fine, but after flashing the SD card, the EV3 itself has an interface with unreadable text (((
